package main
// DO NOT EDIT: generated by github.com/metaleap/vscode-appz/src/gen/gen-golang.ts via github.com/metaleap/vscode-appz/src/gen/main.ts

import (
	. "github.com/metaleap/vscode-appz/libs/go"
)

func demo_Commands_GetCommands() {
	vsc.Commands().GetCommands(false, func(items []string) {
		var opts QuickPickOptions
		opts = */*sorryButSuchIsCodeGenSometimes...*/new(QuickPickOptions)
		opts.IgnoreFocusOut = true
		opts.PlaceHolder = strFmt("Retrieved {0} command ID(s)", len(items))
		vsc.Window().ShowQuickPick2(items, &opts, nil, quit)
	})
}

func demo_Languages_GetLanguages() {
	vsc.Languages().GetLanguages(func(items []string) {
		var opts QuickPickOptions
		opts = */*sorryButSuchIsCodeGenSometimes...*/new(QuickPickOptions)
		opts.IgnoreFocusOut = true
		opts.PlaceHolder = strFmt("Retrieved {0} language ID(s)", len(items))
		vsc.Window().ShowQuickPick2(items, &opts, nil, quit)
	})
}

