package main
// DO NOT EDIT: generated by github.com/metaleap/vscode-appz/src/gen/gen-golang.ts via github.com/metaleap/vscode-appz/src/gen/main.ts

import (
	. "github.com/metaleap/vscode-appz/libs/go"
)

func demo_Commands_GetCommands() {
	vsc.Commands().GetCommands(false, func(cmds []string) {
		var opts QuickPickOptions
		opts = */*sorryButSuchIsCodeGenSometimes...*/new(QuickPickOptions)
		opts.IgnoreFocusOut = true
		opts.PlaceHolder = strFmt("Retrieved {0} command IDs:", len(cmds))
		vsc.Window().ShowQuickPick2(cmds, &opts, nil, quit)
	})
}

func demo_Languages_GetLanguages() {
	vsc.Languages().GetLanguages(func(langs []string) {
		var opts QuickPickOptions
		opts = */*sorryButSuchIsCodeGenSometimes...*/new(QuickPickOptions)
		opts.IgnoreFocusOut = true
		opts.PlaceHolder = strFmt("Retrieved {0} language IDs:", len(langs))
		vsc.Window().ShowQuickPick2(langs, &opts, nil, quit)
	})
}

