package vscode

// DO NOT EDIT: generated by github.com/metaleap/vscode-appz/src/gen/gen-golang.ts via github.com/metaleap/vscode-appz/src/gen/main.ts

type Impl interface {
	Window
}

type MessageOptions struct {
	Modal bool `json:"modal,omitempty"`
}

type MessageItem struct {
	Title             string      `json:"title"`
	IsCloseAffordance bool        `json:"isCloseAffordance,omitempty"`
	Tag               interface{} `json:"tag,omitempty"`
}

type InputBoxOptions struct {
	Value          string              `json:"value,omitempty"`
	ValueSelection []int               `json:"valueSelection,omitempty"`
	Prompt         string              `json:"prompt,omitempty"`
	PlaceHolder    string              `json:"placeHolder,omitempty"`
	Password       bool                `json:"password,omitempty"`
	IgnoreFocusOut bool                `json:"ignoreFocusOut,omitempty"`
	ValidateInput  func(string) string `json:"-"`
}

type Window interface {
	ShowErrorMessage1(message string, items []string, andThen func(string))
	ShowErrorMessage2(message string, options MessageOptions, items []string, andThen func(string))
	ShowErrorMessage3(message string, items []MessageItem, andThen func(MessageItem))
	ShowErrorMessage4(message string, options MessageOptions, items []MessageItem, andThen func(MessageItem))
	ShowInformationMessage1(message string, items []string, andThen func(string))
	ShowInformationMessage2(message string, options MessageOptions, items []string, andThen func(string))
	ShowInformationMessage3(message string, items []MessageItem, andThen func(MessageItem))
	ShowInformationMessage4(message string, options MessageOptions, items []MessageItem, andThen func(MessageItem))
	ShowWarningMessage1(message string, items []string, andThen func(string))
	ShowWarningMessage2(message string, options MessageOptions, items []string, andThen func(string))
	ShowWarningMessage3(message string, items []MessageItem, andThen func(MessageItem))
	ShowWarningMessage4(message string, options MessageOptions, items []MessageItem, andThen func(MessageItem))
	ShowInputBox(options *InputBoxOptions, andThen func(string))
}

func (me *impl) ShowErrorMessage1(message string, items []string, andThen func(string)) {
	msg := msgOutgoing{Ns: "window", Name: "showErrorMessage1", Payload: make(map[string]interface{}, 2)}
	msg.Payload["message"] = message
	msg.Payload["items"] = items
	var on func(...interface{})
	on = func(...interface{}) {

	}
	me.send(&msg, on)
}

func (me *impl) ShowErrorMessage2(message string, options MessageOptions, items []string, andThen func(string)) {
	msg := msgOutgoing{Ns: "window", Name: "showErrorMessage2", Payload: make(map[string]interface{}, 3)}
	msg.Payload["message"] = message
	msg.Payload["options"] = options
	msg.Payload["items"] = items
	var on func(...interface{})
	on = func(...interface{}) {

	}
	me.send(&msg, on)
}

func (me *impl) ShowErrorMessage3(message string, items []MessageItem, andThen func(MessageItem)) {
	msg := msgOutgoing{Ns: "window", Name: "showErrorMessage3", Payload: make(map[string]interface{}, 2)}
	msg.Payload["message"] = message
	msg.Payload["items"] = items
	var on func(...interface{})
	on = func(...interface{}) {

	}
	me.send(&msg, on)
}

func (me *impl) ShowErrorMessage4(message string, options MessageOptions, items []MessageItem, andThen func(MessageItem)) {
	msg := msgOutgoing{Ns: "window", Name: "showErrorMessage4", Payload: make(map[string]interface{}, 3)}
	msg.Payload["message"] = message
	msg.Payload["options"] = options
	msg.Payload["items"] = items
	var on func(...interface{})
	on = func(...interface{}) {

	}
	me.send(&msg, on)
}

func (me *impl) ShowInformationMessage1(message string, items []string, andThen func(string)) {
	msg := msgOutgoing{Ns: "window", Name: "showInformationMessage1", Payload: make(map[string]interface{}, 2)}
	msg.Payload["message"] = message
	msg.Payload["items"] = items
	var on func(...interface{})
	on = func(...interface{}) {

	}
	me.send(&msg, on)
}

func (me *impl) ShowInformationMessage2(message string, options MessageOptions, items []string, andThen func(string)) {
	msg := msgOutgoing{Ns: "window", Name: "showInformationMessage2", Payload: make(map[string]interface{}, 3)}
	msg.Payload["message"] = message
	msg.Payload["options"] = options
	msg.Payload["items"] = items
	var on func(...interface{})
	on = func(...interface{}) {

	}
	me.send(&msg, on)
}

func (me *impl) ShowInformationMessage3(message string, items []MessageItem, andThen func(MessageItem)) {
	msg := msgOutgoing{Ns: "window", Name: "showInformationMessage3", Payload: make(map[string]interface{}, 2)}
	msg.Payload["message"] = message
	msg.Payload["items"] = items
	var on func(...interface{})
	on = func(...interface{}) {

	}
	me.send(&msg, on)
}

func (me *impl) ShowInformationMessage4(message string, options MessageOptions, items []MessageItem, andThen func(MessageItem)) {
	msg := msgOutgoing{Ns: "window", Name: "showInformationMessage4", Payload: make(map[string]interface{}, 3)}
	msg.Payload["message"] = message
	msg.Payload["options"] = options
	msg.Payload["items"] = items
	var on func(...interface{})
	on = func(...interface{}) {

	}
	me.send(&msg, on)
}

func (me *impl) ShowWarningMessage1(message string, items []string, andThen func(string)) {
	msg := msgOutgoing{Ns: "window", Name: "showWarningMessage1", Payload: make(map[string]interface{}, 2)}
	msg.Payload["message"] = message
	msg.Payload["items"] = items
	var on func(...interface{})
	on = func(...interface{}) {

	}
	me.send(&msg, on)
}

func (me *impl) ShowWarningMessage2(message string, options MessageOptions, items []string, andThen func(string)) {
	msg := msgOutgoing{Ns: "window", Name: "showWarningMessage2", Payload: make(map[string]interface{}, 3)}
	msg.Payload["message"] = message
	msg.Payload["options"] = options
	msg.Payload["items"] = items
	var on func(...interface{})
	on = func(...interface{}) {

	}
	me.send(&msg, on)
}

func (me *impl) ShowWarningMessage3(message string, items []MessageItem, andThen func(MessageItem)) {
	msg := msgOutgoing{Ns: "window", Name: "showWarningMessage3", Payload: make(map[string]interface{}, 2)}
	msg.Payload["message"] = message
	msg.Payload["items"] = items
	var on func(...interface{})
	on = func(...interface{}) {

	}
	me.send(&msg, on)
}

func (me *impl) ShowWarningMessage4(message string, options MessageOptions, items []MessageItem, andThen func(MessageItem)) {
	msg := msgOutgoing{Ns: "window", Name: "showWarningMessage4", Payload: make(map[string]interface{}, 3)}
	msg.Payload["message"] = message
	msg.Payload["options"] = options
	msg.Payload["items"] = items
	var on func(...interface{})
	on = func(...interface{}) {

	}
	me.send(&msg, on)
}

func (me *impl) ShowInputBox(options *InputBoxOptions, andThen func(string)) {
	msg := msgOutgoing{Ns: "window", Name: "showInputBox", Payload: make(map[string]interface{}, 1)}
	msg.Payload["options"] = options
	var on func(...interface{})
	on = func(...interface{}) {

	}
	me.send(&msg, on)
}
