package vscode

// DO NOT EDIT: generated by github.com/metaleap/vscode-appz/src/gen/gen-golang.ts via github.com/metaleap/vscode-appz/src/gen/main.ts

type Protocol interface {
	Window() Window
}

func (me *impl) Window() Window { return me }

type MessageOptions struct {
	Modal   bool `json:"modal,omitempty"`
	AppzTag Any  `json:"appzTag,omitempty"`
}

type MessageItem struct {
	Title             string `json:"title"`
	IsCloseAffordance bool   `json:"isCloseAffordance,omitempty"`
	AppzTag           Any    `json:"appzTag,omitempty"`
}

type InputBoxOptions struct {
	Value          string              `json:"value,omitempty"`
	ValueSelection []int               `json:"valueSelection,omitempty"`
	Prompt         string              `json:"prompt,omitempty"`
	PlaceHolder    string              `json:"placeHolder,omitempty"`
	Password       bool                `json:"password,omitempty"`
	IgnoreFocusOut bool                `json:"ignoreFocusOut,omitempty"`
	ValidateInput  func(string) string `json:"-"`
	AppzTag        Any                 `json:"appzTag,omitempty"`
}

type Window interface {
	ShowErrorMessage1(message string, items []string, andThen func(result string, failure Any))
	ShowErrorMessage2(message string, options MessageOptions, items []string, andThen func(result string, failure Any))
	ShowErrorMessage3(message string, items []MessageItem, andThen func(result MessageItem, failure Any))
	ShowErrorMessage4(message string, options MessageOptions, items []MessageItem, andThen func(result MessageItem, failure Any))
	ShowInformationMessage1(message string, items []string, andThen func(result string, failure Any))
	ShowInformationMessage2(message string, options MessageOptions, items []string, andThen func(result string, failure Any))
	ShowInformationMessage3(message string, items []MessageItem, andThen func(result MessageItem, failure Any))
	ShowInformationMessage4(message string, options MessageOptions, items []MessageItem, andThen func(result MessageItem, failure Any))
	ShowWarningMessage1(message string, items []string, andThen func(result string, failure Any))
	ShowWarningMessage2(message string, options MessageOptions, items []string, andThen func(result string, failure Any))
	ShowWarningMessage3(message string, items []MessageItem, andThen func(result MessageItem, failure Any))
	ShowWarningMessage4(message string, options MessageOptions, items []MessageItem, andThen func(result MessageItem, failure Any))
	ShowInputBox(options *InputBoxOptions, andThen func(result string, failure Any))
}

func (me *impl) ShowErrorMessage1(message string, items []string, andThen func(result string, failure Any)) {
	msg := msgOutgoing{Ns: "window", Name: "showErrorMessage1", Payload: make(map[string]Any, 2)}
	msg.Payload["message"] = message
	msg.Payload["items"] = items

	var on func(Any, bool)
	if andThen != nil {
		on = func(payload Any, isFail bool) {
			var result string
			var failure Any
			if isFail {
				failure = payload
			} else {
				var ok bool
				result, ok = payload.(string)
				if !ok {
					failure = payload
				}
			}
			andThen(result, failure)
		}
	}

	me.send(&msg, on)
}

func (me *impl) ShowErrorMessage2(message string, options MessageOptions, items []string, andThen func(result string, failure Any)) {
	msg := msgOutgoing{Ns: "window", Name: "showErrorMessage2", Payload: make(map[string]Any, 3)}
	msg.Payload["message"] = message
	msg.Payload["options"] = options
	msg.Payload["items"] = items

	var on func(Any, bool)
	if andThen != nil {
		on = func(payload Any, isFail bool) {
			var result string
			var failure Any
			if isFail {
				failure = payload
			} else {
				var ok bool
				result, ok = payload.(string)
				if !ok {
					failure = payload
				}
			}
			andThen(result, failure)
		}
	}

	me.send(&msg, on)
}

func (me *impl) ShowErrorMessage3(message string, items []MessageItem, andThen func(result MessageItem, failure Any)) {
	msg := msgOutgoing{Ns: "window", Name: "showErrorMessage3", Payload: make(map[string]Any, 2)}
	msg.Payload["message"] = message
	msg.Payload["items"] = items

	var on func(Any, bool)
	if andThen != nil {
		on = func(payload Any, isFail bool) {
			var result MessageItem
			var failure Any
			if isFail {
				failure = payload
			} else {
				var ok bool
				ok = result.populateFrom(payload)
				if !ok {
					failure = payload
				}
			}
			andThen(result, failure)
		}
	}

	me.send(&msg, on)
}

func (me *impl) ShowErrorMessage4(message string, options MessageOptions, items []MessageItem, andThen func(result MessageItem, failure Any)) {
	msg := msgOutgoing{Ns: "window", Name: "showErrorMessage4", Payload: make(map[string]Any, 3)}
	msg.Payload["message"] = message
	msg.Payload["options"] = options
	msg.Payload["items"] = items

	var on func(Any, bool)
	if andThen != nil {
		on = func(payload Any, isFail bool) {
			var result MessageItem
			var failure Any
			if isFail {
				failure = payload
			} else {
				var ok bool
				ok = result.populateFrom(payload)
				if !ok {
					failure = payload
				}
			}
			andThen(result, failure)
		}
	}

	me.send(&msg, on)
}

func (me *impl) ShowInformationMessage1(message string, items []string, andThen func(result string, failure Any)) {
	msg := msgOutgoing{Ns: "window", Name: "showInformationMessage1", Payload: make(map[string]Any, 2)}
	msg.Payload["message"] = message
	msg.Payload["items"] = items

	var on func(Any, bool)
	if andThen != nil {
		on = func(payload Any, isFail bool) {
			var result string
			var failure Any
			if isFail {
				failure = payload
			} else {
				var ok bool
				result, ok = payload.(string)
				if !ok {
					failure = payload
				}
			}
			andThen(result, failure)
		}
	}

	me.send(&msg, on)
}

func (me *impl) ShowInformationMessage2(message string, options MessageOptions, items []string, andThen func(result string, failure Any)) {
	msg := msgOutgoing{Ns: "window", Name: "showInformationMessage2", Payload: make(map[string]Any, 3)}
	msg.Payload["message"] = message
	msg.Payload["options"] = options
	msg.Payload["items"] = items

	var on func(Any, bool)
	if andThen != nil {
		on = func(payload Any, isFail bool) {
			var result string
			var failure Any
			if isFail {
				failure = payload
			} else {
				var ok bool
				result, ok = payload.(string)
				if !ok {
					failure = payload
				}
			}
			andThen(result, failure)
		}
	}

	me.send(&msg, on)
}

func (me *impl) ShowInformationMessage3(message string, items []MessageItem, andThen func(result MessageItem, failure Any)) {
	msg := msgOutgoing{Ns: "window", Name: "showInformationMessage3", Payload: make(map[string]Any, 2)}
	msg.Payload["message"] = message
	msg.Payload["items"] = items

	var on func(Any, bool)
	if andThen != nil {
		on = func(payload Any, isFail bool) {
			var result MessageItem
			var failure Any
			if isFail {
				failure = payload
			} else {
				var ok bool
				ok = result.populateFrom(payload)
				if !ok {
					failure = payload
				}
			}
			andThen(result, failure)
		}
	}

	me.send(&msg, on)
}

func (me *impl) ShowInformationMessage4(message string, options MessageOptions, items []MessageItem, andThen func(result MessageItem, failure Any)) {
	msg := msgOutgoing{Ns: "window", Name: "showInformationMessage4", Payload: make(map[string]Any, 3)}
	msg.Payload["message"] = message
	msg.Payload["options"] = options
	msg.Payload["items"] = items

	var on func(Any, bool)
	if andThen != nil {
		on = func(payload Any, isFail bool) {
			var result MessageItem
			var failure Any
			if isFail {
				failure = payload
			} else {
				var ok bool
				ok = result.populateFrom(payload)
				if !ok {
					failure = payload
				}
			}
			andThen(result, failure)
		}
	}

	me.send(&msg, on)
}

func (me *impl) ShowWarningMessage1(message string, items []string, andThen func(result string, failure Any)) {
	msg := msgOutgoing{Ns: "window", Name: "showWarningMessage1", Payload: make(map[string]Any, 2)}
	msg.Payload["message"] = message
	msg.Payload["items"] = items

	var on func(Any, bool)
	if andThen != nil {
		on = func(payload Any, isFail bool) {
			var result string
			var failure Any
			if isFail {
				failure = payload
			} else {
				var ok bool
				result, ok = payload.(string)
				if !ok {
					failure = payload
				}
			}
			andThen(result, failure)
		}
	}

	me.send(&msg, on)
}

func (me *impl) ShowWarningMessage2(message string, options MessageOptions, items []string, andThen func(result string, failure Any)) {
	msg := msgOutgoing{Ns: "window", Name: "showWarningMessage2", Payload: make(map[string]Any, 3)}
	msg.Payload["message"] = message
	msg.Payload["options"] = options
	msg.Payload["items"] = items

	var on func(Any, bool)
	if andThen != nil {
		on = func(payload Any, isFail bool) {
			var result string
			var failure Any
			if isFail {
				failure = payload
			} else {
				var ok bool
				result, ok = payload.(string)
				if !ok {
					failure = payload
				}
			}
			andThen(result, failure)
		}
	}

	me.send(&msg, on)
}

func (me *impl) ShowWarningMessage3(message string, items []MessageItem, andThen func(result MessageItem, failure Any)) {
	msg := msgOutgoing{Ns: "window", Name: "showWarningMessage3", Payload: make(map[string]Any, 2)}
	msg.Payload["message"] = message
	msg.Payload["items"] = items

	var on func(Any, bool)
	if andThen != nil {
		on = func(payload Any, isFail bool) {
			var result MessageItem
			var failure Any
			if isFail {
				failure = payload
			} else {
				var ok bool
				ok = result.populateFrom(payload)
				if !ok {
					failure = payload
				}
			}
			andThen(result, failure)
		}
	}

	me.send(&msg, on)
}

func (me *impl) ShowWarningMessage4(message string, options MessageOptions, items []MessageItem, andThen func(result MessageItem, failure Any)) {
	msg := msgOutgoing{Ns: "window", Name: "showWarningMessage4", Payload: make(map[string]Any, 3)}
	msg.Payload["message"] = message
	msg.Payload["options"] = options
	msg.Payload["items"] = items

	var on func(Any, bool)
	if andThen != nil {
		on = func(payload Any, isFail bool) {
			var result MessageItem
			var failure Any
			if isFail {
				failure = payload
			} else {
				var ok bool
				ok = result.populateFrom(payload)
				if !ok {
					failure = payload
				}
			}
			andThen(result, failure)
		}
	}

	me.send(&msg, on)
}

func (me *impl) ShowInputBox(options *InputBoxOptions, andThen func(result string, failure Any)) {
	msg := msgOutgoing{Ns: "window", Name: "showInputBox", Payload: make(map[string]Any, 1)}
	msg.Payload["options"] = options

	var on func(Any, bool)
	if andThen != nil {
		on = func(payload Any, isFail bool) {
			var result string
			var failure Any
			if isFail {
				failure = payload
			} else {
				var ok bool
				result, ok = payload.(string)
				if !ok {
					failure = payload
				}
			}
			andThen(result, failure)
		}
	}

	me.send(&msg, on)
}

func (me *MessageItem) populateFrom(payload Any) bool {
	m, ok := payload.(map[string]Any)
	if ok && m != nil {
		{
			val, exists := m["title"]
			if exists {
				if val != nil {
					var ok bool
					me.Title, ok = val.(string)
					if !ok {
						return false
					}
				} else if true {
					return false
				}
			} else if true {
				return false
			}
		}
		{
			val, exists := m["isCloseAffordance"]
			if exists {
				if val != nil {
					var ok bool
					me.IsCloseAffordance, ok = val.(bool)
					if !ok {
						return false
					}
				} else if false {
					return false
				}
			} else if false {
				return false
			}
		}
		{
			val, exists := m["appzTag"]
			if exists {
				if val != nil {
					me.AppzTag = val
				} else if false {
					return false
				}
			} else if false {
				return false
			}
		}
		return true
	}
	return false
}
