// DO NOT EDIT: generated by github.com/metaleap/vscode-appz/src/gen/gen-csharp.ts via github.com/metaleap/vscode-appz/src/gen/main.ts
namespace VscAppzDemo {
	using System;
	using System.Collections.Generic;
	using VscAppz;
	using any = System.Object;
	using dict = System.Collections.Generic.Dictionary<string, object>;

	public static partial class App {
		private static void demo_Commands_GetCommands() {
			vsc.Commands.GetCommands(false, (string[] cmds) => {
				QuickPickOptions opts = default;
				opts = new QuickPickOptions();
				opts.IgnoreFocusOut = true;
				opts.PlaceHolder = strFmt("Retrieved {0} command IDs:", cmds.Length);
				vsc.Window.ShowQuickPick(cmds, opts, null, quit);
			});
		}
		private static void demo_Languages_GetLanguages() {
			vsc.Languages.GetLanguages((string[] langs) => {
				QuickPickOptions opts = default;
				opts = new QuickPickOptions();
				opts.IgnoreFocusOut = true;
				opts.PlaceHolder = strFmt("Retrieved {0} language IDs:", langs.Length);
				vsc.Window.ShowQuickPick(langs, opts, null, quit);
			});
		}
}}
