// DO NOT EDIT: generated by github.com/metaleap/vscode-appz/src/gen/gen-vscext.ts via github.com/metaleap/vscode-appz/src/gen/main.ts

import * as vscode from 'vscode'

import * as ppio from './procspipeio'

type MessageOptions = vscode.MessageOptions
interface MessageItem extends vscode.MessageItem {
	my?: { [_: string]: any }
}
interface InputBoxOptions extends vscode.InputBoxOptions {
	validateInput_AppzFuncId: string
}

export function handle(msg: ppio.IpcMsg, proc: ppio.Proc): [Thenable<any>, string[]] {
	const idxdot = msg.qName.lastIndexOf('.')
	const [apiname, methodname] = (idxdot > 0) ? [msg.qName.slice(0, idxdot), msg.qName.slice(idxdot + 1)] : ['', msg.qName]
	switch (apiname) {
		case "window":
			switch (methodname) {
				case "showErrorMessage1": {
					let ctoks: string[] = undefined
					const arg_message = (msg.data['message']) as string
					const arg_items = (msg.data['items'] || []) as string[]
					return [vscode.window.showErrorMessage(arg_message, ...arg_items, ), ctoks]
				}
				case "showErrorMessage2": {
					let ctoks: string[] = undefined
					const arg_message = (msg.data['message']) as string
					const arg_options = (msg.data['options']) as MessageOptions
					const arg_items = (msg.data['items'] || []) as string[]
					return [vscode.window.showErrorMessage(arg_message, arg_options, ...arg_items, ), ctoks]
				}
				case "showErrorMessage3": {
					let ctoks: string[] = undefined
					const arg_message = (msg.data['message']) as string
					const arg_items = (msg.data['items'] || []) as MessageItem[]
					return [vscode.window.showErrorMessage(arg_message, ...arg_items, ), ctoks]
				}
				case "showErrorMessage4": {
					let ctoks: string[] = undefined
					const arg_message = (msg.data['message']) as string
					const arg_options = (msg.data['options']) as MessageOptions
					const arg_items = (msg.data['items'] || []) as MessageItem[]
					return [vscode.window.showErrorMessage(arg_message, arg_options, ...arg_items, ), ctoks]
				}
				case "showInformationMessage1": {
					let ctoks: string[] = undefined
					const arg_message = (msg.data['message']) as string
					const arg_items = (msg.data['items'] || []) as string[]
					return [vscode.window.showInformationMessage(arg_message, ...arg_items, ), ctoks]
				}
				case "showInformationMessage2": {
					let ctoks: string[] = undefined
					const arg_message = (msg.data['message']) as string
					const arg_options = (msg.data['options']) as MessageOptions
					const arg_items = (msg.data['items'] || []) as string[]
					return [vscode.window.showInformationMessage(arg_message, arg_options, ...arg_items, ), ctoks]
				}
				case "showInformationMessage3": {
					let ctoks: string[] = undefined
					const arg_message = (msg.data['message']) as string
					const arg_items = (msg.data['items'] || []) as MessageItem[]
					return [vscode.window.showInformationMessage(arg_message, ...arg_items, ), ctoks]
				}
				case "showInformationMessage4": {
					let ctoks: string[] = undefined
					const arg_message = (msg.data['message']) as string
					const arg_options = (msg.data['options']) as MessageOptions
					const arg_items = (msg.data['items'] || []) as MessageItem[]
					return [vscode.window.showInformationMessage(arg_message, arg_options, ...arg_items, ), ctoks]
				}
				case "showWarningMessage1": {
					let ctoks: string[] = undefined
					const arg_message = (msg.data['message']) as string
					const arg_items = (msg.data['items'] || []) as string[]
					return [vscode.window.showWarningMessage(arg_message, ...arg_items, ), ctoks]
				}
				case "showWarningMessage2": {
					let ctoks: string[] = undefined
					const arg_message = (msg.data['message']) as string
					const arg_options = (msg.data['options']) as MessageOptions
					const arg_items = (msg.data['items'] || []) as string[]
					return [vscode.window.showWarningMessage(arg_message, arg_options, ...arg_items, ), ctoks]
				}
				case "showWarningMessage3": {
					let ctoks: string[] = undefined
					const arg_message = (msg.data['message']) as string
					const arg_items = (msg.data['items'] || []) as MessageItem[]
					return [vscode.window.showWarningMessage(arg_message, ...arg_items, ), ctoks]
				}
				case "showWarningMessage4": {
					let ctoks: string[] = undefined
					const arg_message = (msg.data['message']) as string
					const arg_options = (msg.data['options']) as MessageOptions
					const arg_items = (msg.data['items'] || []) as MessageItem[]
					return [vscode.window.showWarningMessage(arg_message, arg_options, ...arg_items, ), ctoks]
				}
				case "showInputBox": {
					let ctoks: string[] = undefined
					const arg_options = (msg.data['options']) as InputBoxOptions
					if (arg_options.validateInput_AppzFuncId && arg_options.validateInput_AppzFuncId.length)
						arg_options.validateInput = (a0) => proc.callBack(arg_options.validateInput_AppzFuncId, a0)
					const arg_token = proc.canceller(msg.data['token'])
					if (arg_token) {
						if (ctoks === undefined)
							ctoks = []
						ctoks.push(msg.data['token'] as string)
					}
					return [vscode.window.showInputBox(arg_options, arg_token, ), ctoks]
				}
				default:
					throw (methodname)
			}
		default:
			throw (apiname)
	}
}

