// DO NOT EDIT: generated by github.com/metaleap/vscode-appz/src/gen/gen-csharp.ts via github.com/metaleap/vscode-appz/src/gen/main.ts
namespace Vscode {
	using System;

	public interface IProtocol {
		IWindow Window { get; }
	}

	internal partial class impl : IProtocol {
		IWindow IProtocol.Window { get { return this; } }
	}

	public class MessageOptions {
		public bool Modal;

		public MessageOptions() { }
		public MessageOptions(bool modal) =>
			Modal = modal;
	}

	public class MessageItem {
		public string Title;
		public bool IsCloseAffordance;
		public object AppzTag;

		public MessageItem() { }
		public MessageItem(string title, bool isCloseAffordance, object appzTag) =>
			(Title, IsCloseAffordance, AppzTag) = (title, isCloseAffordance, appzTag);
	}

	public class InputBoxOptions {
		public string Value;
		public (int, int) ValueSelection;
		public string Prompt;
		public string PlaceHolder;
		public bool Password;
		public bool IgnoreFocusOut;
		public Func<string, string> ValidateInput;

		public InputBoxOptions() { }
		public InputBoxOptions(string value, (int, int) valueSelection, string prompt, string placeHolder, bool password, bool ignoreFocusOut, Func<string, string> validateInput) =>
			(Value, ValueSelection, Prompt, PlaceHolder, Password, IgnoreFocusOut, ValidateInput) = (value, valueSelection, prompt, placeHolder, password, ignoreFocusOut, validateInput);
	}

	public interface IWindow {
		void ShowErrorMessage(string message, string[] items, Action<string> andThen);
		void ShowErrorMessage(string message, MessageOptions options, string[] items, Action<string> andThen);
		void ShowErrorMessage(string message, MessageItem[] items, Action<MessageItem> andThen);
		void ShowErrorMessage(string message, MessageOptions options, MessageItem[] items, Action<MessageItem> andThen);
		void ShowInformationMessage(string message, string[] items, Action<string> andThen);
		void ShowInformationMessage(string message, MessageOptions options, string[] items, Action<string> andThen);
		void ShowInformationMessage(string message, MessageItem[] items, Action<MessageItem> andThen);
		void ShowInformationMessage(string message, MessageOptions options, MessageItem[] items, Action<MessageItem> andThen);
		void ShowWarningMessage(string message, string[] items, Action<string> andThen);
		void ShowWarningMessage(string message, MessageOptions options, string[] items, Action<string> andThen);
		void ShowWarningMessage(string message, MessageItem[] items, Action<MessageItem> andThen);
		void ShowWarningMessage(string message, MessageOptions options, MessageItem[] items, Action<MessageItem> andThen);
		void ShowInputBox(InputBoxOptions options, Action<string> andThen);
	}

	internal partial class impl : IWindow {
		void IWindow.ShowErrorMessage(string message, string[] items, Action<string> andThen) {
		}

		void IWindow.ShowErrorMessage(string message, MessageOptions options, string[] items, Action<string> andThen) {
		}

		void IWindow.ShowErrorMessage(string message, MessageItem[] items, Action<MessageItem> andThen) {
		}

		void IWindow.ShowErrorMessage(string message, MessageOptions options, MessageItem[] items, Action<MessageItem> andThen) {
		}

		void IWindow.ShowInformationMessage(string message, string[] items, Action<string> andThen) {
		}

		void IWindow.ShowInformationMessage(string message, MessageOptions options, string[] items, Action<string> andThen) {
		}

		void IWindow.ShowInformationMessage(string message, MessageItem[] items, Action<MessageItem> andThen) {
		}

		void IWindow.ShowInformationMessage(string message, MessageOptions options, MessageItem[] items, Action<MessageItem> andThen) {
		}

		void IWindow.ShowWarningMessage(string message, string[] items, Action<string> andThen) {
		}

		void IWindow.ShowWarningMessage(string message, MessageOptions options, string[] items, Action<string> andThen) {
		}

		void IWindow.ShowWarningMessage(string message, MessageItem[] items, Action<MessageItem> andThen) {
		}

		void IWindow.ShowWarningMessage(string message, MessageOptions options, MessageItem[] items, Action<MessageItem> andThen) {
		}

		void IWindow.ShowInputBox(InputBoxOptions options, Action<string> andThen) {
		}
	}

}
